### ISSUE TITLE
Application using django-bitcoin is unaware of transaction fees

### ISSUE THREAD

**Issue by wladston** [kangasbros/django-bitcoin#5]
If a transaction fee is required from completing a transaction, it will get debited from the main wallet.dat account, and the user won't get informed. We need a way to raise an exception when a transaction fee from a transaction happens.

**Comment by kangasbros** [comment]
Now the transaction fee is deducted from the wallet. This is suboptimal solution, because wallet balance can go to negative that way. However, it is very minor issue in practice, and because it is impossible currently to calculate the fee beforehand, this won't fix for the time being.

(However, it is possible to patch your bitcoin client to not do the transaction if fees are added).
